name: Coccinelle
on:
  pull_request:
  push:
jobs:
  coccinelle:
    name: Coccinelle
    runs-on: ubuntu-latest
    container:
      # coccinelle version in ubuntu-latest (20.04) is too old so we run
      # this in impish (21.10) container which has the version we need
      image: ubuntu:impish

    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get -y install coccinelle

    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    - name: Run coccinelle
      run: |
        ./scripts/coccinelle.sh

    - name: Save coccinelle.diff
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coccinelle.diff
        path: coccinelle.diff

