name: 'Close stale issues'
"on":
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: "
            Dear Author,
            \n\n
            This issue has been automatically marked as stale due to lack of
            activity. With only the issue description that is currently
            provided, we do not have enough information to take action. If you
            have or find the answers we would need, please reach out. Otherwise,
            this issue will be closed in 30 days.
            \n\n
            Thank you!
            "

          close-issue-message: "
            Dear Author,
            \n\n
            We are closing this issue due to lack of activity. Feel free to add
            a comment to this issue if you can provide more information and we
            will re-open it.
            \n\n
            Thank you!
            "

          # Don't process PRs
          days-before-stale: -1

          # Process only issues
          days-before-issue-stale: 60
          days-before-issue-close: 30

          # Add this label after 'days-before-issue-stale' days to mark it as stale
          stale-issue-label: 'no-activity'

          # Process only issues that contain the label 'waiting-for-author'
          only-labels: 'waiting-for-author'

          # Stale only issues with one of these labels
          any-of-issue-labels: 'bug,enhancement,stale-issue'

          # Exclude issues with the 'in-progress' label
          exempt-issue-labels: 'in-progress'

          # Exclude assigned issues
          exempt-all-assignees: true

